# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12c76d8e7dc713af9e3993a4e7cef3ca7952ed7f30f58f2aedd2b90127bccb6b7ed1fcf4cf30d27e3bcbf080d947157b62a54b0ad1a707b01b53edb050946c54

test:
  secret_key_base: ab0abb42fc62c8d17dd8af41705ef657ebdbf477604dd28f4082500dc193f48f1e70d8125bf83d383acc338a6e3b895ce9d45acea589f1ac4aa5b808e95c9670

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
